services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      - rabbitmq
  
  producer:
    depends_on:
      - rabbitmq
    build: producer/.
    working_dir: /
    networks:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - 8080:8080
  
  consumer:
    depends_on:
      - rabbitmq
      - producer
    build: consumer/.
    working_dir: /
    networks:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - 8081:8081
networks:
  rabbitmq:
    driver: bridge